name: Manual Artifact Download Test

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    environment:
      name: staging

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # Usually good practice to start with a fresh checkout

    - name: List downloaded files
      run: ls -R # This will list all files in the download directory

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: backendTag # Replace with the exact name of your artifact
        path: artifacts/tagVersions/frontend  # Optional: define a directory to download to