name: Deploy Docker Compose

on:
  pull_request:
    types:
      - closed


jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.base.ref, 'release/staging')
    environment:
      name: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Download image tag
        run: |
          TMKBRAIN_TAG=${cat tmk_brain_latest_image_tag.txt}
          TMKFACE_TAG=${cat tmk_face_latest_image_tag.txt}
          echo "TMKBRAIN_TAG = ${TMKBRAIN_TAG}"
          echo "TMKFACE_TAG = ${TMKFACE_TAG}"


      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Docker Compose
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'cd /home/ec2-user/TmkPalantir && /.run-docker-compose.bash ${${TMKBRAIN_TAG}} ${{TMKFACE_TAG}}'