name: Upload Artifact

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add your build and test steps here

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backendTag
          path: ./